// <auto-generated />
using System;
using LicentaInAngular.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicentaInAngular.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250418132702_RemovalCardIdCard")]
    partial class RemovalCardIdCard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Carduri", b =>
                {
                    b.Property<int>("IdCard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCard"));

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataExpirare")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumarCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdCard");

                    b.HasIndex("NumarCard")
                        .IsUnique();

                    b.ToTable("Carduri");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Adrese_Useri", b =>
                {
                    b.Property<int>("idAU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAU"));

                    b.Property<int>("IdAdresa")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("idAU");

                    b.HasIndex("IdAdresa");

                    b.HasIndex("IdUser");

                    b.ToTable("Adrese_Useri");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Categorii", b =>
                {
                    b.Property<int>("IdCategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategorie"));

                    b.Property<string>("DenumireCategorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescriereCategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategorie");

                    b.HasIndex("DenumireCategorie")
                        .IsUnique();

                    b.ToTable("Categorii");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Imagini", b =>
                {
                    b.Property<int>("idImagine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idImagine"));

                    b.Property<byte[]>("Fisier")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("IdProdus")
                        .HasColumnType("int");

                    b.HasKey("idImagine");

                    b.HasIndex("IdProdus");

                    b.ToTable("Imagini");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Judete", b =>
                {
                    b.Property<int>("IdJudet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJudet"));

                    b.Property<string>("DenumireJudet")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdTara")
                        .HasColumnType("int");

                    b.HasKey("IdJudet");

                    b.HasIndex("DenumireJudet")
                        .IsUnique();

                    b.HasIndex("IdTara");

                    b.ToTable("Judete");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Localitati", b =>
                {
                    b.Property<int>("IdLocalitate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalitate"));

                    b.Property<string>("DenumireLocalitate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdJudet")
                        .HasColumnType("int");

                    b.HasKey("IdLocalitate");

                    b.HasIndex("IdJudet");

                    b.ToTable("Localitati");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Preturi_Produs", b =>
                {
                    b.Property<int>("idPP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPP"));

                    b.Property<decimal?>("Comision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataExpirare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInceput")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProdus")
                        .HasColumnType("int");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idPP");

                    b.HasIndex("IdProdus");

                    b.ToTable("Preturi_Produs");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Strazi", b =>
                {
                    b.Property<int>("IdStrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStrada"));

                    b.Property<string>("DenumireStrada")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdLocalitate")
                        .HasColumnType("int");

                    b.Property<int>("Nr")
                        .HasColumnType("int");

                    b.HasKey("IdStrada");

                    b.HasIndex("DenumireStrada")
                        .IsUnique();

                    b.HasIndex("IdLocalitate");

                    b.ToTable("Strazi");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Tari", b =>
                {
                    b.Property<int>("IdTara")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTara"));

                    b.Property<string>("DenumireTara")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdTara");

                    b.HasIndex("DenumireTara")
                        .IsUnique();

                    b.ToTable("Tari");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Useri_Carduri", b =>
                {
                    b.Property<int>("idUC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUC"));

                    b.Property<DateTime>("DataAdaugarii")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCard")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("idUC");

                    b.HasIndex("IdCard");

                    b.HasIndex("IdUser");

                    b.ToTable("Useri_Carduri");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Vopsea", b =>
                {
                    b.Property<int>("idVopsea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVopsea"));

                    b.Property<string>("An")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCuloare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdProdus")
                        .HasColumnType("int");

                    b.Property<string>("MarcaMasinii")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerieCaroserie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipVopsea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idVopsea");

                    b.HasIndex("IdProdus");

                    b.ToTable("Vopsele");
                });

            modelBuilder.Entity("LicentaInAngular.Server.Models.Adresa", b =>
                {
                    b.Property<int>("IdAdresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdresa"));

                    b.Property<string>("Apartament")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bloc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdStrada")
                        .HasColumnType("int");

                    b.Property<string>("Scara")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAdresa");

                    b.HasIndex("IdStrada");

                    b.ToTable("Adrese");
                });

            modelBuilder.Entity("LicentaInAngular.Server.Models.Comanda", b =>
                {
                    b.Property<int>("IdComanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComanda"));

                    b.Property<int?>("Card_CCidUC")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ETA")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAdresa")
                        .HasColumnType("int");

                    b.Property<int>("IdCard_CC")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlaced")
                        .HasColumnType("bit");

                    b.Property<double>("PretTotal")
                        .HasColumnType("float");

                    b.HasKey("IdComanda");

                    b.HasIndex("Card_CCidUC");

                    b.HasIndex("IdAdresa");

                    b.HasIndex("IdUser");

                    b.ToTable("Comenzi");
                });

            modelBuilder.Entity("LicentaInAngular.Server.Models.Cos", b =>
                {
                    b.Property<int>("idCos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCos"));

                    b.Property<string>("CodUnic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCreare")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("idCos");

                    b.HasIndex("IdUser");

                    b.ToTable("Cosuri");
                });

            modelBuilder.Entity("LicentaInAngular.Server.Models.Persoana", b =>
                {
                    b.Property<int>("IdPersoana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersoana"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tipPersoana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPersoana");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telefon")
                        .IsUnique()
                        .HasFilter("[Telefon] IS NOT NULL");

                    b.ToTable("Persoane");
                });

            modelBuilder.Entity("LicentaInAngular.Server.Models.Produs", b =>
                {
                    b.Property<int>("IdProdus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProdus"));

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsteSpray")
                        .HasColumnType("bit");

                    b.Property<int>("IdCategorie")
                        .HasColumnType("int");

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Valabil")
                        .HasColumnType("bit");

                    b.HasKey("IdProdus");

                    b.HasIndex("IdCategorie");

                    b.HasIndex("IdUser");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LicentaInAngular.Server.Models.Subcomanda", b =>
                {
                    b.Property<int>("IdSubcomanda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubcomanda"));

                    b.Property<int>("IdComanda")
                        .HasColumnType("int");

                    b.Property<int>("IdProdus")
                        .HasColumnType("int");

                    b.Property<int>("TotalSubproduse")
                        .HasColumnType("int");

                    b.HasKey("IdSubcomanda");

                    b.HasIndex("IdComanda");

                    b.HasIndex("IdProdus");

                    b.ToTable("Subcomenzi");
                });

            modelBuilder.Entity("LicentaInAngular.Server.Models.Subprodus", b =>
                {
                    b.Property<int>("IdSubprodus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubprodus"));

                    b.Property<int>("IdProdus")
                        .HasColumnType("int");

                    b.Property<bool>("Valabil")
                        .HasColumnType("bit");

                    b.Property<int?>("idCos")
                        .HasColumnType("int");

                    b.HasKey("IdSubprodus");

                    b.HasIndex("IdProdus");

                    b.HasIndex("idCos");

                    b.ToTable("SubProduse");
                });

            modelBuilder.Entity("LicentaInAngular.Server.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<int>("IdPersoana")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdUser");

                    b.HasIndex("IdPersoana");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Adrese_Useri", b =>
                {
                    b.HasOne("LicentaInAngular.Server.Models.Adresa", "Adrese")
                        .WithMany()
                        .HasForeignKey("IdAdresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LicentaInAngular.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adrese");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Imagini", b =>
                {
                    b.HasOne("LicentaInAngular.Server.Models.Produs", "Produs")
                        .WithMany()
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Judete", b =>
                {
                    b.HasOne("LicentaInAngular.Server.DataLayer.Models.Tari", "Tari")
                        .WithMany()
                        .HasForeignKey("IdTara")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tari");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Localitati", b =>
                {
                    b.HasOne("LicentaInAngular.Server.DataLayer.Models.Judete", "Judete")
                        .WithMany()
                        .HasForeignKey("IdJudet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Judete");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Preturi_Produs", b =>
                {
                    b.HasOne("LicentaInAngular.Server.Models.Produs", "Produs")
                        .WithMany()
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Strazi", b =>
                {
                    b.HasOne("LicentaInAngular.Server.DataLayer.Models.Localitati", "Localitati")
                        .WithMany()
                        .HasForeignKey("IdLocalitate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localitati");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Useri_Carduri", b =>
                {
                    b.HasOne("Carduri", "Card")
                        .WithMany()
                        .HasForeignKey("IdCard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LicentaInAngular.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LicentaInAngular.Server.DataLayer.Models.Vopsea", b =>
                {
                    b.HasOne("LicentaInAngular.Server.Models.Produs", "Produs")
                        .WithMany()
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("LicentaInAngular.Server.Models.Adresa", b =>
                {
                    b.HasOne("LicentaInAngular.Server.DataLayer.Models.Strazi", "Strazi")
                        .WithMany()
                        .HasForeignKey("IdStrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strazi");
                });

            modelBuilder.Entity("LicentaInAngular.Server.Models.Comanda", b =>
                {
                    b.HasOne("LicentaInAngular.Server.DataLayer.Models.Useri_Carduri", "Card_CC")
                        .WithMany()
                        .HasForeignKey("Card_CCidUC");

                    b.HasOne("LicentaInAngular.Server.Models.Adresa", "Adresa")
                        .WithMany()
                        .HasForeignKey("IdAdresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LicentaInAngular.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adresa");

                    b.Navigation("Card_CC");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LicentaInAngular.Server.Models.Cos", b =>
                {
                    b.HasOne("LicentaInAngular.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LicentaInAngular.Server.Models.Produs", b =>
                {
                    b.HasOne("LicentaInAngular.Server.DataLayer.Models.Categorii", "Categorii")
                        .WithMany()
                        .HasForeignKey("IdCategorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LicentaInAngular.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser");

                    b.Navigation("Categorii");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LicentaInAngular.Server.Models.Subcomanda", b =>
                {
                    b.HasOne("LicentaInAngular.Server.Models.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("IdComanda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LicentaInAngular.Server.Models.Produs", "Produs")
                        .WithMany()
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("LicentaInAngular.Server.Models.Subprodus", b =>
                {
                    b.HasOne("LicentaInAngular.Server.Models.Produs", "Produs")
                        .WithMany()
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LicentaInAngular.Server.Models.Cos", "Cos")
                        .WithMany()
                        .HasForeignKey("idCos");

                    b.Navigation("Cos");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("LicentaInAngular.Server.Models.User", b =>
                {
                    b.HasOne("LicentaInAngular.Server.Models.Persoana", "Persoana")
                        .WithMany()
                        .HasForeignKey("IdPersoana")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persoana");
                });
#pragma warning restore 612, 618
        }
    }
}
