// 🔹 DTO for User Registration
// 🔹 DTO for User Registration
export interface RegisterUserDto {
  Username: string;
  Password: string;
  Persoana: {
    Nume: string;
    Prenume: string;
    Email: string;
    tipPersoana: string; // "Fizica" or "Juridica"
    Telefon: string;
    Rol: "Owner" | "Administrator" | "Participant"; // New field for role ion
  };
}
export interface SearchProdusDTO {
  idProdus: number;
  nume: string;
  idUser: number | null;
}


export interface ProdusReducereDTO {
  idProdus: number;
  nume: string;
  descriere: string;
  imagine: string;
  pretVechi: number;
  pretReducere: number;
  categorie: string;
  vendor: string;
}


export interface ProdusComandaDTO {
  numeProdus: string;
  cantitate: number;
}

export interface ComandaUserDTO {
  idComanda: number;
  eta: string;
  isPlaced: boolean;
  pretTotal: number;

  // Adresă completă
  tara: string;
  judet: string;
  localitate: string;
  strada: string;
  nr: number;
  bloc: string;
  scara: string;
  etaj: string;
  apartament: string;

  produse: ProdusComandaDTO[];
}


export interface SimularePlataDTO {
  idUser: number;
  idAdresa: number;
  idCard: number;
  numarCard: string;
  dataExpirare: string;
  cvv: string;
}

export interface CardulDTO {
  idCard: number;
  numarCard: string;
  cvv: string;
  dataExpirare: Date;
}


export interface LoginDto {
  username: string;
  password: string;
}

export interface UpdateUserDto {
  username?: string;
  password?: string;
  persoana: PersoanaDto;
}

export interface PersoanaDto {
  nume: string;
  prenume: string;
  email: string;
  tipPersoana: string;
  telefon: string;
  rol: "Owner" | "Administrator" | "Participant"; // Restrict values
}

export interface CategoryDTO {
  denumireCategorie: string;
  descriereCategorie: string;
}

export interface SubcomandaDTO {
  idProdus: number;
  totalSubproduse: number;
  idComanda: number;
}

//Sectiunea de adrese
export interface AdresaDTO {
  idAdresa?: number;  // Opțional, deoarece la crearea unei noi adrese nu există încă identificator
  Strada: string;     // Numele străzii
  Nr: number;         // Numărul străzii
  Bloc?: string;      // Bloc (opțional)
  Scara?: string;     // Scară (opțional)
  Etaj?: string;      // Etaj (opțional)
  Apartament?: string; // Apartament (opțional)
  Localitate: string; // Numele localității
  Judet: string;     // Numele județului
  Tara: string;      // Numele țării
}

// Poți păstra aceste definiții într-un fișier models/NewDTOs.ts, de exemplu

export interface AdresaNestedDTO {
  Bloc?: string;
  Scara?: string;
  Etaj?: string;
  Apartament?: string;
  Strazi: StraziDTO; // Observă că aici 'Strazi' este un obiect
}

export interface StraziDTO {
  DenumireStrada: string;
  Nr: number;
  Localitati: LocalitatiDTO;
}

export interface LocalitatiDTO {
  DenumireLocalitate: string;
  Judete: JudeteDTO;
}

export interface JudeteDTO {
  DenumireJudet: string;
  Tari: TariDTO;
}

export interface TariDTO {
  DenumireTara: string;
}


export interface UserAddressDTO {
  idUser: number;
  idAdresa: number;
}

//Sectiunea de carduri


export interface CardDTO {
  numarCard: string;
  cvv: string;
  dataExpirare: string; // Format: YYYY-MM-DD
}

export interface UserCardDTO {
  idUser: number;
  idCard: number;
}

// Sectiunea de Categorii

export interface CategoryDTO {
  denumireCategorie: string;
  descriereCategorie: string;
}

//Sectiunea de Comenzi

// 🔹 Order (Comanda)
export interface ComandaDTO {
  idComanda?: number;  // Optional, generated by DB
  idUser: number;
  idAdresa: number;
  pretTotal: number;
  eta?: string; // Estimated Time of Arrival
}

// 🔹 Payment Details for Order Submission
export interface ComandaPaymentDTO {
  payment: {
    amountInBani: number;       // ex. 12300 (pentru 123.00 RON)
    paymentMethodId: string;    // ex. "pm_xxx"
    description: string;        // ex. "Plată vopsea auto"
  };
  comanda: {
    idUser: number;
    idAdresa: number;
    pretTotal: number;
    // poți adăuga isPlaced, idCard, etc. dacă le folosești
  };
}
//Sectiunea de Cos

// 🔹 DTO for Cart Operations
export interface CartDTO {
  idCos: number;
  idUser: number;
}

// 🔹 DTO for Updating Subproducts in Cart
export interface SubprodusUpdateDTO {
  idCos: number;
  idProdus: number;
}

// 🔹 DTO for Cart Product Details
export interface CartProductDTO {
  idProdus: number;
  quantity: number;
  produs: {
    idProdus: number;
    nume: string;
    pret: number;
  };
}

// 🔹 DTO for Cart Details Response
export interface CartDetailsDTO {
  cart: CartDTO;
  items: CartProductDTO[];
}


//Sectiunea pentru Persoane
// 🔹 DTO for Persoana (Person Management)
export interface PersoanaDTO {
  nume: string;
  prenume: string;
  email: string;
  tipPersoana: string; // Either "Fizica" or "Juridica"
  telefon: string;
}

// 🔹 DTO for Product Creation & Update
export interface ProductDTO {
  [x: string]: any;
  idProdus?: number;  // Optional (only for updates)
  nume: string;
  descriere: string;
  esteSpray: boolean;
  valabil: boolean;
  idCategorie?: number;
  idUser: number;
  pret?: number;  // Only for creation (stored separately in DB)
  codCuloare?: string;
  imagine?: File | null;  // Image file to be uploaded
}
export interface ProdusDTO {
  ProdusId: number;
  Nume: string;
  Descriere?: string;
  EsteSprayText: string;
  Imagine: string | null;
  Pret: number;
  Valabil: boolean;
  Categorie: string;
  Vendor: string;
  IdUser?: number; // <-- adăugat
}
// 🔹 DTO pentru încărcarea produsului (cu imagine și ID utilizator)
export interface ProdusIncarcatDTO {
  Nume: string;
  Descriere?: string;
  EsteSprayText: string;
  Imagine?: File | null;
  Pret: number;
  Valabil: boolean;
  Categorie: string;
  Vendor?: string;
  IdUser: number;
}


// 🔹 DTO for Searching Products
export interface ProductSearchDTO {
  nume: string;
}

//Sectiunea pentru subcomenzi

// 🔹 DTO for Subcomanda (Creating & Fetching)
export interface SubcomandaDTO {
  idSubcomanda?: number;  // Optional (only for updates & deletions)
  idProdus: number;
  totalSubproduse: number;
  idComanda: number;
}

// 🔹 DTO for Fetching Products by Order or User
export interface FetchSubcomandaDTO {
  idComanda?: number;
  idUser?: number;
}

// 🔹 DTO for Deleting a Subcomanda by Order and Product
export interface DeleteSubcomandaDTO {
  idComanda: number;
  idProdus: number;
}

//Sectiunea pentru Subproduse

// 🔹 DTO for Subprodus (Creating & Fetching)
export interface SubprodusDTO {
  idSubprodus?: number;  // Optional (only for updates & deletions)
  idProdus: number;
  valabil: boolean;
  idCos?: number;  // Optional (only when linked to a cart)
}

// 🔹 DTO for Fetching Products in a Cart
export interface FetchSubprodusDTO {
  idCos: number;
}

// 🔹 DTO for Deleting a Subprodus by Cart and Product
export interface DeleteSubprodusDTO {
  idCos: number;
  idProdus: number;
}


//Sectiunea pentru vopsele

// 🔹 DTO for Creating a Custom Paint and Adding to Cart
export interface CreateVopseaSiAdaugaInCosDTO {
  idUser: number;
  tipVopsea: string; // Either "spray" or normal
  marcaMasinii: string;
  codCuloare: string;
  model: string;
  an: number;
  serieCaroserie: string;
  detaliiSuplimentare?: string;
  cantitate: number;
}

// 🔹 DTO for Created Paint Response
export interface VopseaResponseDTO {
  message: string;
  produs: {
    idProdus: number;
    nume: string;
    descriere: string;
    esteSpray: boolean;
    imagine?: string; // Base64 image (if exists)
    pret: number;
    valabil: boolean;
    categorie: string;
    idUser?: number;
  };
  idVopsea: number;
  idCos: number;
  subproduseCreateInCos: number;
}
export interface UpdateDetaliiUserDTO {
  username?: string;
  password?: string;
  nume?: string;
  prenume?: string;
  email?: string;
  telefon?: string;
}
